// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGtcskkL5U4HTMPmrGT2NEbKtU-LpXdhE',
    appId: '1:497052885543:web:efea7a82afd73e7a456402',
    messagingSenderId: '497052885543',
    projectId: 'cryptotrade-61b57',
    authDomain: 'cryptotrade-61b57.firebaseapp.com',
    storageBucket: 'cryptotrade-61b57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDminmuKPgzxzjNd0AKeUWHEYaCba8wU8c',
    appId: '1:497052885543:android:02eed07c86285b97456402',
    messagingSenderId: '497052885543',
    projectId: 'cryptotrade-61b57',
    storageBucket: 'cryptotrade-61b57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXEnue0z9QsStif0JIPJ4pnV7ou6XlpNw',
    appId: '1:497052885543:ios:a67fbf0c5c17abab456402',
    messagingSenderId: '497052885543',
    projectId: 'cryptotrade-61b57',
    storageBucket: 'cryptotrade-61b57.firebasestorage.app',
    iosBundleId: 'com.lrngroup.cryptotrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXEnue0z9QsStif0JIPJ4pnV7ou6XlpNw',
    appId: '1:497052885543:ios:a67fbf0c5c17abab456402',
    messagingSenderId: '497052885543',
    projectId: 'cryptotrade-61b57',
    storageBucket: 'cryptotrade-61b57.firebasestorage.app',
    iosBundleId: 'com.lrngroup.cryptotrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGtcskkL5U4HTMPmrGT2NEbKtU-LpXdhE',
    appId: '1:497052885543:web:6fcd8934a9005a78456402',
    messagingSenderId: '497052885543',
    projectId: 'cryptotrade-61b57',
    authDomain: 'cryptotrade-61b57.firebaseapp.com',
    storageBucket: 'cryptotrade-61b57.firebasestorage.app',
  );
}
